### ISSUE TITLE
mount render issue

### ISSUE THREAD

**Issue by v42** [WebPlatformForEmbedded/Lightning#30]
Hi,

I've experienced some issues with the `mount` property:

```js
export default class App extends ux.App {
    static _template() {
        return {
            Header: {
                rect: true,
                w: 1920,
                h: 50,
                color: 0xff005500,
                Title: {
                    x: w => w - 50,
                    y: 30,
                    mountX: 1,
                    mountY: 0.5, text: { text: 'Header' }
                }
            }
        }
    }
}
```

If I have this code, it renders like this:

![image](https://user-images.githubusercontent.com/974782/62367730-b4516d80-b52a-11e9-99f8-c066e7808954.png)

If I add the same code to the live demo (or in a component within a project), it renders as expected (please notice `window.innerWidth`, since the demo panel is smaller than 1920!):

```js
class LiveDemo extends lng.Application {
    static _template() {
        return {
            Header: {
                rect: true,
                w: window.innerWidth,
                h: 50,
                color: 0xff005500,
                Title: {
                    x: w => w - 50,
                    y: 30,
                    mountX: 1,
                    mountY: 0.5, text: { text: 'Header' }
                }
            }
        }
    };
}
````
![image](https://user-images.githubusercontent.com/974782/62368350-a00e7000-b52c-11e9-8095-a379a2c3d1be.png)

Thanks!

**Comment by v42** [comment]
Btw, using Lightning in the SDK with the blueprint. Thanks!

**Comment by g-zachar** [comment]
Looks like it was fixed in recent Lightning (exact change: https://github.com/WebPlatformForEmbedded/Lightning/commit/97444951be90b1354d746e5cc553ccffbb94898b)

I'll leave it open until fully confirmed.

**Comment by woutermeek** [comment]
@v42 can you check if this is fixed as @g-zachar is mentioning?

**Comment by v42** [comment]
@woutermeek not fixed on SDK yet, I've created an issue there:
https://github.com/WebPlatformForEmbedded/Lightning-SDK/issues/7
